apiVersion: v1
kind: ConfigMap
metadata:
    name: ui-cm-nginx
data:
    nginx.conf: |
        user nginx;
        worker_processes  1;
        events {
            worker_connections  10240;
        }
        http {
            upstream backend {
                server api;
            }
            server {
                listen       80;
                server_name  localhost;
                location / {
                    root   /usr/share/nginx/html;
                    index  index.html index.htm;
                }
            }
        }